# Use the Maven image with Java 17
FROM maven:3.8.3-openjdk-17-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the entire project directory to the container
COPY . .

# Run 'mvn install' to build the project
RUN mvn install

EXPOSE 8080

# Command to run the application (replace 'your-application.jar' with the actual name of the JAR or WAR file generated by Maven)
CMD ["java", "-jar", "target/demo-0.0.1-SNAPSHOT.jar"]

